use simfolk; 

SELECT * FROM SONG;
SELECT * FROM SONG_TO_ATTRIBUTE;
SELECT * FROM TERM;
SELECT * FROM TERM_TOKENIZED;
SELECT * FROM TERM_GROUP;
SELECT * FROM TERM_GROUP_TO_TERM;
SELECT * FROM WEIGHTED_TERM_GROUP;

TRUNCATE TABLE term_tokenized;
TRUNCATE TABLE term;
